test

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -38,7 +38,14 @@ stages:
         scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: |
-          userId=$(az ad user list --display-name "$(vaultAdmin)" --query "[].id" --output tsv)
+          userId=$(az ad user list --display-name "$(vaultAdmin)" --query "[0].id" --output tsv)
+          
+          if [[ -z "$userId" ]]; then
+            echo "##vso[task.logissue type=error]Failed to fetch User ID for $(vaultAdmin)."
+            exit 1
+          fi
+
+          echo "User ID: $userId"
           echo "##vso[task.setvariable variable=adminObjectID;isOutput=true;isSecret=true]$userId"
   
     - script: |
@@ -57,6 +64,12 @@ stages:
         scriptLocation: 'inlineScript'
         inlineScript: |
           adminEmail=$(az ad user show --id "$(adminObjectID)" --query "mail" --output tsv)
+          
+          if [[ -z "$adminEmail" ]]; then
+            echo "##vso[task.logissue type=error]Admin Email could not be retrieved."
+            exit 1
+          fi
+
           echo "Fetched Admin Email: $adminEmail"
           echo "##vso[task.setvariable variable=adminEmail;isOutput=true;isSecret=true]$adminEmail"
 
